package main

// VulnerablePackage represents a vulnerable NPM package
type VulnerablePackage struct {
	Name     string
	Versions []string
}

// GetVulnerablePackages returns a list of vulnerable NPM packages
func GetVulnerablePackages() []VulnerablePackage {
	return []VulnerablePackage{
		{Name: "02-echo", Versions: []string{"0.0.7"}},
		{Name: "@accordproject/concerto-analysis", Versions: []string{"3.24.1"}},
		{Name: "@accordproject/concerto-linter", Versions: []string{"3.24.1"}},
		{Name: "@accordproject/concerto-linter-default-ruleset", Versions: []string{"3.24.1"}},
		{Name: "@accordproject/concerto-metamodel", Versions: []string{"3.12.5"}},
		{Name: "@accordproject/concerto-types", Versions: []string{"3.24.1"}},
		{Name: "@accordproject/markdown-it-cicero", Versions: []string{"0.16.26"}},
		{Name: "@accordproject/template-engine", Versions: []string{"2.7.2"}},
		{Name: "@actbase/css-to-react-native-transform", Versions: []string{"1.0.3"}},
		{Name: "@actbase/native", Versions: []string{"0.1.32"}},
		{Name: "@actbase/node-server", Versions: []string{"1.1.19"}},
		{Name: "@actbase/react-absolute", Versions: []string{"0.8.3"}},
		{Name: "@actbase/react-daum-postcode", Versions: []string{"1.0.5"}},
		{Name: "@actbase/react-kakaosdk", Versions: []string{"0.9.27"}},
		{Name: "@actbase/react-native-actionsheet", Versions: []string{"1.0.3"}},
		{Name: "@actbase/react-native-devtools", Versions: []string{"0.1.3"}},
		{Name: "@actbase/react-native-fast-image", Versions: []string{"8.5.13"}},
		{Name: "@actbase/react-native-kakao-channel", Versions: []string{"1.0.2"}},
		{Name: "@actbase/react-native-kakao-navi", Versions: []string{"2.0.4"}},
		{Name: "@actbase/react-native-less-transformer", Versions: []string{"1.0.6"}},
		{Name: "@actbase/react-native-naver-login", Versions: []string{"1.0.1"}},
		{Name: "@actbase/react-native-simple-video", Versions: []string{"1.0.13"}},
		{Name: "@actbase/react-native-tiktok", Versions: []string{"1.1.3"}},
		{Name: "@afetcan/api", Versions: []string{"0.0.13"}},
		{Name: "@afetcan/storage", Versions: []string{"0.0.27"}},
		{Name: "@ahmedhfarag/ngx-perfect-scrollbar", Versions: []string{"20.0.20"}},
		{Name: "@ahmedhfarag/ngx-virtual-scroller", Versions: []string{"4.0.4"}},
		{Name: "@alaan/s2s-auth", Versions: []string{"2.0.3"}},
		{Name: "@alexadark/amadeus-api", Versions: []string{"1.0.4"}},
		{Name: "@alexadark/gatsby-theme-events", Versions: []string{"1.0.1"}},
		{Name: "@alexadark/gatsby-theme-wordpress-blog", Versions: []string{"2.0.1"}},
		{Name: "@alexadark/reusable-functions", Versions: []string{"1.5.1"}},
		{Name: "@alexcolls/nuxt-socket.io", Versions: []string{"0.0.7", "0.0.8"}},
		{Name: "@alexcolls/nuxt-ux", Versions: []string{"0.6.1", "0.6.2"}},
		{Name: "@antstackio/eslint-config-antstack", Versions: []string{"0.0.3"}},
		{Name: "@antstackio/express-graphql-proxy", Versions: []string{"0.2.8"}},
		{Name: "@antstackio/graphql-body-parser", Versions: []string{"0.1.1"}},
		{Name: "@antstackio/json-to-graphql", Versions: []string{"1.0.3"}},
		{Name: "@antstackio/shelbysam", Versions: []string{"1.1.7"}},
		{Name: "@art-ws/common", Versions: []string{"2.0.22", "2.0.28"}},
		{Name: "@art-ws/config-eslint", Versions: []string{"2.0.4", "2.0.5"}},
		{Name: "@art-ws/config-ts", Versions: []string{"2.0.7", "2.0.8"}},
		{Name: "@art-ws/db-context", Versions: []string{"2.0.24"}},
		{Name: "@art-ws/di", Versions: []string{"2.0.28", "2.0.32"}},
		{Name: "@art-ws/di-node", Versions: []string{"2.0.13"}},
		{Name: "@art-ws/eslint", Versions: []string{"1.0.5", "1.0.6"}},
		{Name: "@art-ws/fastify-http-server", Versions: []string{"2.0.24", "2.0.27"}},
		{Name: "@art-ws/http-server", Versions: []string{"2.0.21", "2.0.25"}},
		{Name: "@art-ws/openapi", Versions: []string{"0.1.9", "0.1.12"}},
		{Name: "@art-ws/package-base", Versions: []string{"1.0.5", "1.0.6"}},
		{Name: "@art-ws/prettier", Versions: []string{"1.0.5", "1.0.6"}},
		{Name: "@art-ws/slf", Versions: []string{"2.0.15", "2.0.22"}},
		{Name: "@art-ws/ssl-info", Versions: []string{"1.0.9", "1.0.10"}},
		{Name: "@art-ws/web-app", Versions: []string{"1.0.3", "1.0.4"}},
		{Name: "@aryanhussain/my-angular-lib", Versions: []string{"0.0.23"}},
		{Name: "@asyncapi/avro-schema-parser", Versions: []string{"3.0.25", "3.0.26"}},
		{Name: "@asyncapi/bundler", Versions: []string{"0.6.5", "0.6.6"}},
		{Name: "@asyncapi/cli", Versions: []string{"4.1.2", "4.1.3"}},
		{Name: "@asyncapi/converter", Versions: []string{"1.6.3", "1.6.4"}},
		{Name: "@asyncapi/diff", Versions: []string{"0.5.1", "0.5.2"}},
		{Name: "@asyncapi/dotnet-rabbitmq-template", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "@asyncapi/edavisualiser", Versions: []string{"1.2.1", "1.2.2"}},
		{Name: "@asyncapi/generator", Versions: []string{"2.8.5", "2.8.6"}},
		{Name: "@asyncapi/generator-components", Versions: []string{"0.3.2", "0.3.3"}},
		{Name: "@asyncapi/generator-helpers", Versions: []string{"0.2.1", "0.2.2"}},
		{Name: "@asyncapi/generator-react-sdk", Versions: []string{"1.1.4", "1.1.5"}},
		{Name: "@asyncapi/go-watermill-template", Versions: []string{"0.2.76", "0.2.77"}},
		{Name: "@asyncapi/html-template", Versions: []string{"3.3.2", "3.3.3"}},
		{Name: "@asyncapi/java-spring-cloud-stream-template", Versions: []string{"0.13.5", "0.13.6"}},
		{Name: "@asyncapi/java-spring-template", Versions: []string{"1.6.1", "1.6.2"}},
		{Name: "@asyncapi/java-template", Versions: []string{"0.3.5", "0.3.6"}},
		{Name: "@asyncapi/keeper", Versions: []string{"0.0.2", "0.0.3"}},
		{Name: "@asyncapi/markdown-template", Versions: []string{"1.6.8", "1.6.9"}},
		{Name: "@asyncapi/modelina", Versions: []string{"5.10.2", "5.10.3"}},
		{Name: "@asyncapi/modelina-cli", Versions: []string{"5.10.2", "5.10.3"}},
		{Name: "@asyncapi/multi-parser", Versions: []string{"2.2.1", "2.2.2"}},
		{Name: "@asyncapi/nodejs-template", Versions: []string{"3.0.5", "3.0.6"}},
		{Name: "@asyncapi/nodejs-ws-template", Versions: []string{"0.10.1", "0.10.2"}},
		{Name: "@asyncapi/nunjucks-filters", Versions: []string{"2.1.1", "2.1.2"}},
		{Name: "@asyncapi/openapi-schema-parser", Versions: []string{"3.0.25", "3.0.26"}},
		{Name: "@asyncapi/optimizer", Versions: []string{"1.0.5", "1.0.6"}},
		{Name: "@asyncapi/parser", Versions: []string{"3.4.1", "3.4.2"}},
		{Name: "@asyncapi/php-template", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "@asyncapi/problem", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "@asyncapi/protobuf-schema-parser", Versions: []string{"3.5.2", "3.5.3", "3.6.1"}},
		{Name: "@asyncapi/python-paho-template", Versions: []string{"0.2.14", "0.2.15"}},
		{Name: "@asyncapi/react-component", Versions: []string{"2.6.6", "2.6.7"}},
		{Name: "@asyncapi/server-api", Versions: []string{"0.16.24", "0.16.25"}},
		{Name: "@asyncapi/specs", Versions: []string{"6.10.1", "6.8.2", "6.8.3", "6.9.1"}},
		{Name: "@asyncapi/studio", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "@asyncapi/web-component", Versions: []string{"2.6.6", "2.6.7"}},
		{Name: "@bdkinc/knex-ibmi", Versions: []string{"0.5.7"}},
		{Name: "@browserbasehq/bb9", Versions: []string{"1.2.21"}},
		{Name: "@browserbasehq/director-ai", Versions: []string{"1.0.3"}},
		{Name: "@browserbasehq/mcp", Versions: []string{"2.1.1"}},
		{Name: "@browserbasehq/mcp-server-browserbase", Versions: []string{"2.4.2"}},
		{Name: "@browserbasehq/sdk-functions", Versions: []string{"0.0.4"}},
		{Name: "@browserbasehq/stagehand", Versions: []string{"3.0.4"}},
		{Name: "@browserbasehq/stagehand-docs", Versions: []string{"1.0.1"}},
		{Name: "@caretive/caret-cli", Versions: []string{"0.0.2"}},
		{Name: "@chtijs/eslint-config", Versions: []string{"1.0.1"}},
		{Name: "@clausehq/flows-step-httprequest", Versions: []string{"0.1.14"}},
		{Name: "@clausehq/flows-step-jsontoxml", Versions: []string{"0.1.14"}},
		{Name: "@clausehq/flows-step-mqtt", Versions: []string{"0.1.14"}},
		{Name: "@clausehq/flows-step-sendgridemail", Versions: []string{"0.1.14"}},
		{Name: "@clausehq/flows-step-taskscreateurl", Versions: []string{"0.1.14"}},
		{Name: "@cllbk/ghl", Versions: []string{"1.3.1"}},
		{Name: "@commute/bloom", Versions: []string{"1.0.3"}},
		{Name: "@commute/market-data", Versions: []string{"1.0.2"}},
		{Name: "@commute/market-data-chartjs", Versions: []string{"2.3.1"}},
		{Name: "@crowdstrike/commitlint", Versions: []string{"8.1.1", "8.1.2"}},
		{Name: "@crowdstrike/falcon-shoelace", Versions: []string{"0.4.1", "0.4.2"}},
		{Name: "@crowdstrike/foundry-js", Versions: []string{"0.19.1", "0.19.2"}},
		{Name: "@crowdstrike/glide-core", Versions: []string{"0.34.2", "0.34.3"}},
		{Name: "@crowdstrike/logscale-dashboard", Versions: []string{"1.205.1", "1.205.2"}},
		{Name: "@crowdstrike/logscale-file-editor", Versions: []string{"1.205.1", "1.205.2"}},
		{Name: "@crowdstrike/logscale-parser-edit", Versions: []string{"1.205.1", "1.205.2"}},
		{Name: "@crowdstrike/logscale-search", Versions: []string{"1.205.1", "1.205.2"}},
		{Name: "@crowdstrike/tailwind-toucan-base", Versions: []string{"5.0.1", "5.0.2"}},
		{Name: "@ctrl/deluge", Versions: []string{"7.2.1", "7.2.2"}},
		{Name: "@ctrl/golang-template", Versions: []string{"1.4.2", "1.4.3"}},
		{Name: "@ctrl/magnet-link", Versions: []string{"4.0.3", "4.0.4"}},
		{Name: "@ctrl/ngx-codemirror", Versions: []string{"7.0.1", "7.0.2"}},
		{Name: "@ctrl/ngx-csv", Versions: []string{"6.0.1", "6.0.2"}},
		{Name: "@ctrl/ngx-emoji-mart", Versions: []string{"9.2.1", "9.2.2"}},
		{Name: "@ctrl/ngx-rightclick", Versions: []string{"4.0.1", "4.0.2"}},
		{Name: "@ctrl/qbittorrent", Versions: []string{"9.7.1", "9.7.2"}},
		{Name: "@ctrl/react-adsense", Versions: []string{"2.0.1", "2.0.2"}},
		{Name: "@ctrl/shared-torrent", Versions: []string{"6.3.1", "6.3.2"}},
		{Name: "@ctrl/tinycolor", Versions: []string{"4.1.1", "4.1.2"}},
		{Name: "@ctrl/torrent-file", Versions: []string{"4.1.1", "4.1.2"}},
		{Name: "@ctrl/transmission", Versions: []string{"7.3.1"}},
		{Name: "@ctrl/ts-base32", Versions: []string{"4.0.1", "4.0.2"}},
		{Name: "@dev-blinq/ai-qa-logic", Versions: []string{"1.0.19"}},
		{Name: "@dev-blinq/blinqioclient", Versions: []string{"1.0.21"}},
		{Name: "@dev-blinq/cucumber-js", Versions: []string{"1.0.131"}},
		{Name: "@dev-blinq/cucumber_client", Versions: []string{"1.0.738"}},
		{Name: "@dev-blinq/ui-systems", Versions: []string{"1.0.93"}},
		{Name: "@ensdomains/address-encoder", Versions: []string{"1.1.5"}},
		{Name: "@ensdomains/blacklist", Versions: []string{"1.0.1"}},
		{Name: "@ensdomains/buffer", Versions: []string{"0.1.2"}},
		{Name: "@ensdomains/ccip-read-cf-worker", Versions: []string{"0.0.4"}},
		{Name: "@ensdomains/ccip-read-dns-gateway", Versions: []string{"0.1.1"}},
		{Name: "@ensdomains/ccip-read-router", Versions: []string{"0.0.7"}},
		{Name: "@ensdomains/ccip-read-worker-viem", Versions: []string{"0.0.4"}},
		{Name: "@ensdomains/content-hash", Versions: []string{"3.0.1"}},
		{Name: "@ensdomains/curvearithmetics", Versions: []string{"1.0.1"}},
		{Name: "@ensdomains/cypress-metamask", Versions: []string{"1.2.1"}},
		{Name: "@ensdomains/dnsprovejs", Versions: []string{"0.5.3"}},
		{Name: "@ensdomains/dnssec-oracle-anchors", Versions: []string{"0.0.2"}},
		{Name: "@ensdomains/dnssecoraclejs", Versions: []string{"0.2.9"}},
		{Name: "@ensdomains/durin", Versions: []string{"0.1.2"}},
		{Name: "@ensdomains/durin-middleware", Versions: []string{"0.0.2"}},
		{Name: "@ensdomains/ens-archived-contracts", Versions: []string{"0.0.3"}},
		{Name: "@ensdomains/ens-avatar", Versions: []string{"1.0.4"}},
		{Name: "@ensdomains/ens-contracts", Versions: []string{"1.6.1"}},
		{Name: "@ensdomains/ens-test-env", Versions: []string{"1.0.2"}},
		{Name: "@ensdomains/ens-validation", Versions: []string{"0.1.1"}},
		{Name: "@ensdomains/ensjs", Versions: []string{"4.0.3"}},
		{Name: "@ensdomains/ensjs-react", Versions: []string{"0.0.5"}},
		{Name: "@ensdomains/eth-ens-namehash", Versions: []string{"2.0.16"}},
		{Name: "@ensdomains/hackathon-registrar", Versions: []string{"1.0.5"}},
		{Name: "@ensdomains/hardhat-chai-matchers-viem", Versions: []string{"0.1.15"}},
		{Name: "@ensdomains/hardhat-toolbox-viem-extended", Versions: []string{"0.0.6"}},
		{Name: "@ensdomains/mock", Versions: []string{"2.1.52"}},
		{Name: "@ensdomains/name-wrapper", Versions: []string{"1.0.1"}},
		{Name: "@ensdomains/offchain-resolver-contracts", Versions: []string{"0.2.2"}},
		{Name: "@ensdomains/op-resolver-contracts", Versions: []string{"0.0.2"}},
		{Name: "@ensdomains/react-ens-address", Versions: []string{"0.0.32"}},
		{Name: "@ensdomains/renewal", Versions: []string{"0.0.13"}},
		{Name: "@ensdomains/renewal-widget", Versions: []string{"0.1.10"}},
		{Name: "@ensdomains/reverse-records", Versions: []string{"1.0.1"}},
		{Name: "@ensdomains/server-analytics", Versions: []string{"0.0.2"}},
		{Name: "@ensdomains/solsha1", Versions: []string{"0.0.4"}},
		{Name: "@ensdomains/subdomain-registrar", Versions: []string{"0.2.4"}},
		{Name: "@ensdomains/test-utils", Versions: []string{"1.3.1"}},
		{Name: "@ensdomains/thorin", Versions: []string{"0.6.51"}},
		{Name: "@ensdomains/ui", Versions: []string{"3.4.6"}},
		{Name: "@ensdomains/unicode-confusables", Versions: []string{"0.1.1"}},
		{Name: "@ensdomains/unruggable-gateways", Versions: []string{"0.0.3"}},
		{Name: "@ensdomains/vite-plugin-i18next-loader", Versions: []string{"4.0.4"}},
		{Name: "@ensdomains/web3modal", Versions: []string{"1.10.2"}},
		{Name: "@everreal/react-charts", Versions: []string{"2.0.1", "2.0.2"}},
		{Name: "@everreal/validate-esmoduleinterop-imports", Versions: []string{"1.4.4", "1.4.5"}},
		{Name: "@everreal/web-analytics", Versions: []string{"0.0.1", "0.0.2"}},
		{Name: "@faq-component/core", Versions: []string{"0.0.4"}},
		{Name: "@faq-component/react", Versions: []string{"1.0.1"}},
		{Name: "@fishingbooker/browser-sync-plugin", Versions: []string{"1.0.5"}},
		{Name: "@fishingbooker/react-loader", Versions: []string{"1.0.7"}},
		{Name: "@fishingbooker/react-pagination", Versions: []string{"2.0.6"}},
		{Name: "@fishingbooker/react-raty", Versions: []string{"2.0.1"}},
		{Name: "@fishingbooker/react-swiper", Versions: []string{"0.1.5"}},
		{Name: "@hapheus/n8n-nodes-pgp", Versions: []string{"1.5.1"}},
		{Name: "@hestjs/core", Versions: []string{"0.2.1"}},
		{Name: "@hestjs/cqrs", Versions: []string{"0.1.6"}},
		{Name: "@hestjs/demo", Versions: []string{"0.1.2"}},
		{Name: "@hestjs/eslint-config", Versions: []string{"0.1.2"}},
		{Name: "@hestjs/logger", Versions: []string{"0.1.6"}},
		{Name: "@hestjs/scalar", Versions: []string{"0.1.7"}},
		{Name: "@hestjs/validation", Versions: []string{"0.1.6"}},
		{Name: "@hover-design/core", Versions: []string{"0.0.1"}},
		{Name: "@hover-design/react", Versions: []string{"0.2.1"}},
		{Name: "@huntersofbook/auth-vue", Versions: []string{"0.4.2"}},
		{Name: "@huntersofbook/core", Versions: []string{"0.5.1"}},
		{Name: "@huntersofbook/core-nuxt", Versions: []string{"0.4.2"}},
		{Name: "@huntersofbook/form-naiveui", Versions: []string{"0.5.1"}},
		{Name: "@huntersofbook/i18n", Versions: []string{"0.8.2"}},
		{Name: "@huntersofbook/ui", Versions: []string{"0.5.1"}},
		{Name: "@hyperlook/telemetry-sdk", Versions: []string{"1.0.19"}},
		{Name: "@ifelsedeveloper/protocol-contracts-svm-idl", Versions: []string{"0.1.2", "0.1.3"}},
		{Name: "@ifings/design-system", Versions: []string{"4.9.2"}},
		{Name: "@ifings/metatron3", Versions: []string{"0.1.5"}},
		{Name: "@jayeshsadhwani/telemetry-sdk", Versions: []string{"1.0.14"}},
		{Name: "@kvytech/cli", Versions: []string{"0.0.7"}},
		{Name: "@kvytech/components", Versions: []string{"0.0.2"}},
		{Name: "@kvytech/habbit-e2e-test", Versions: []string{"0.0.2"}},
		{Name: "@kvytech/medusa-plugin-announcement", Versions: []string{"0.0.8"}},
		{Name: "@kvytech/medusa-plugin-management", Versions: []string{"0.0.5"}},
		{Name: "@kvytech/medusa-plugin-newsletter", Versions: []string{"0.0.5"}},
		{Name: "@kvytech/medusa-plugin-product-reviews", Versions: []string{"0.0.9"}},
		{Name: "@kvytech/medusa-plugin-promotion", Versions: []string{"0.0.2"}},
		{Name: "@kvytech/web", Versions: []string{"0.0.2"}},
		{Name: "@lessondesk/api-client", Versions: []string{"9.12.2", "9.12.3"}},
		{Name: "@lessondesk/babel-preset", Versions: []string{"1.0.1"}},
		{Name: "@lessondesk/electron-group-api-client", Versions: []string{"1.0.3"}},
		{Name: "@lessondesk/eslint-config", Versions: []string{"1.4.2"}},
		{Name: "@lessondesk/material-icons", Versions: []string{"1.0.3"}},
		{Name: "@lessondesk/react-table-context", Versions: []string{"2.0.4"}},
		{Name: "@lessondesk/schoolbus", Versions: []string{"5.2.2", "5.2.3"}},
		{Name: "@livecms/live-edit", Versions: []string{"0.0.32"}},
		{Name: "@livecms/nuxt-live-edit", Versions: []string{"1.9.2"}},
		{Name: "@lokeswari-satyanarayanan/rn-zustand-expo-template", Versions: []string{"1.0.9"}},
		{Name: "@louisle2/core", Versions: []string{"1.0.1"}},
		{Name: "@louisle2/cortex-js", Versions: []string{"0.1.6"}},
		{Name: "@lpdjs/firestore-repo-service", Versions: []string{"1.0.1"}},
		{Name: "@lui-ui/lui-nuxt", Versions: []string{"0.1.1"}},
		{Name: "@lui-ui/lui-tailwindcss", Versions: []string{"0.1.2"}},
		{Name: "@lui-ui/lui-vue", Versions: []string{"1.0.13"}},
		{Name: "@markvivanco/app-version-checker", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "@mcp-use/cli", Versions: []string{"2.2.6", "2.2.7"}},
		{Name: "@mcp-use/inspector", Versions: []string{"0.6.2", "0.6.3"}},
		{Name: "@mcp-use/mcp-use", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "@micado-digital/stadtmarketing-kufstein-external", Versions: []string{"1.90.1"}},
		{Name: "@mizzle-dev/orm", Versions: []string{"0.0.2"}},
		{Name: "@mparpaillon/connector-parse", Versions: []string{"1.0.1"}},
		{Name: "@mparpaillon/imagesloaded", Versions: []string{"4.1.2"}},
		{Name: "@mparpaillon/page", Versions: []string{"1.0.1"}},
		{Name: "@nativescript-community/arraybuffers", Versions: []string{"1.1.6", "1.1.7", "1.1.8"}},
		{Name: "@nativescript-community/gesturehandler", Versions: []string{"2.0.35"}},
		{Name: "@nativescript-community/perms", Versions: []string{"3.0.5", "3.0.6", "3.0.7", "3.0.8"}},
		{Name: "@nativescript-community/sentry", Versions: []string{"4.6.43"}},
		{Name: "@nativescript-community/sqlite", Versions: []string{"3.5.2", "3.5.3", "3.5.4", "3.5.5"}},
		{Name: "@nativescript-community/text", Versions: []string{"1.6.9", "1.6.10", "1.6.11", "1.6.12", "1.6.13"}},
		{Name: "@nativescript-community/typeorm", Versions: []string{"0.2.30", "0.2.31", "0.2.32", "0.2.33"}},
		{Name: "@nativescript-community/ui-collectionview", Versions: []string{"6.0.6"}},
		{Name: "@nativescript-community/ui-document-picker", Versions: []string{"1.1.27", "1.1.28"}},
		{Name: "@nativescript-community/ui-drawer", Versions: []string{"0.1.30"}},
		{Name: "@nativescript-community/ui-image", Versions: []string{"4.5.6"}},
		{Name: "@nativescript-community/ui-label", Versions: []string{"1.3.35", "1.3.36", "1.3.37"}},
		{Name: "@nativescript-community/ui-material-bottom-navigation", Versions: []string{"7.2.72", "7.2.73", "7.2.74", "7.2.75"}},
		{Name: "@nativescript-community/ui-material-bottomsheet", Versions: []string{"7.2.72"}},
		{Name: "@nativescript-community/ui-material-core", Versions: []string{"7.2.72", "7.2.73", "7.2.74", "7.2.75", "7.2.76"}},
		{Name: "@nativescript-community/ui-material-core-tabs", Versions: []string{"7.2.72", "7.2.73", "7.2.74", "7.2.75", "7.2.76"}},
		{Name: "@nativescript-community/ui-material-ripple", Versions: []string{"7.2.72", "7.2.73", "7.2.74", "7.2.75"}},
		{Name: "@nativescript-community/ui-material-tabs", Versions: []string{"7.2.72", "7.2.73", "7.2.74", "7.2.75"}},
		{Name: "@nativescript-community/ui-pager", Versions: []string{"14.1.36", "14.1.37", "14.1.38"}},
		{Name: "@nativescript-community/ui-pulltorefresh", Versions: []string{"2.5.4", "2.5.5", "2.5.6", "2.5.7"}},
		{Name: "@nexe/config-manager", Versions: []string{"0.1.1"}},
		{Name: "@nexe/eslint-config", Versions: []string{"0.1.1"}},
		{Name: "@nexe/logger", Versions: []string{"0.1.3"}},
		{Name: "@nstudio/angular", Versions: []string{"20.0.4", "20.0.5", "20.0.6"}},
		{Name: "@nstudio/focus", Versions: []string{"20.0.4", "20.0.5", "20.0.6"}},
		{Name: "@nstudio/nativescript-checkbox", Versions: []string{"2.0.6", "2.0.7", "2.0.8", "2.0.9"}},
		{Name: "@nstudio/nativescript-loading-indicator", Versions: []string{"5.0.1", "5.0.2", "5.0.3", "5.0.4"}},
		{Name: "@nstudio/ui-collectionview", Versions: []string{"5.1.11", "5.1.12", "5.1.13", "5.1.14"}},
		{Name: "@nstudio/web", Versions: []string{"20.0.4"}},
		{Name: "@nstudio/web-angular", Versions: []string{"20.0.4"}},
		{Name: "@nstudio/xplat", Versions: []string{"20.0.5", "20.0.6", "20.0.7"}},
		{Name: "@nstudio/xplat-utils", Versions: []string{"20.0.5", "20.0.6", "20.0.7"}},
		{Name: "@ntnx/passport-wso2", Versions: []string{"0.0.3"}},
		{Name: "@ntnx/t", Versions: []string{"0.0.101"}},
		{Name: "@oku-ui/accordion", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/alert-dialog", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/arrow", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/aspect-ratio", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/avatar", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/checkbox", Versions: []string{"0.6.3"}},
		{Name: "@oku-ui/collapsible", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/collection", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/dialog", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/direction", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/dismissable-layer", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/focus-guards", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/focus-scope", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/hover-card", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/label", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/menu", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/motion", Versions: []string{"0.4.4"}},
		{Name: "@oku-ui/motion-nuxt", Versions: []string{"0.2.2"}},
		{Name: "@oku-ui/popover", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/popper", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/portal", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/presence", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/primitive", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/primitives", Versions: []string{"0.7.9"}},
		{Name: "@oku-ui/primitives-nuxt", Versions: []string{"0.3.1"}},
		{Name: "@oku-ui/progress", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/provide", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/radio-group", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/roving-focus", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/scroll-area", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/separator", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/slider", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/slot", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/switch", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/tabs", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/toast", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/toggle", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/toggle-group", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/toolbar", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/tooltip", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/use-composable", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/utils", Versions: []string{"0.6.2"}},
		{Name: "@oku-ui/visually-hidden", Versions: []string{"0.6.2"}},
		{Name: "@operato/board", Versions: []string{"9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46", "9.0.47", "9.0.48", "9.0.49", "9.0.50", "9.0.51"}},
		{Name: "@operato/data-grist", Versions: []string{"9.0.29", "9.0.35", "9.0.36", "9.0.37"}},
		{Name: "@operato/graphql", Versions: []string{"9.0.22", "9.0.35", "9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46"}},
		{Name: "@operato/headroom", Versions: []string{"9.0.2", "9.0.35", "9.0.36", "9.0.37"}},
		{Name: "@operato/help", Versions: []string{"9.0.35", "9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46"}},
		{Name: "@operato/i18n", Versions: []string{"9.0.35", "9.0.36", "9.0.37"}},
		{Name: "@operato/input", Versions: []string{"9.0.27", "9.0.35", "9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46", "9.0.47", "9.0.48"}},
		{Name: "@operato/layout", Versions: []string{"9.0.35", "9.0.36", "9.0.37"}},
		{Name: "@operato/popup", Versions: []string{"9.0.22", "9.0.35", "9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46", "9.0.49"}},
		{Name: "@operato/pull-to-refresh", Versions: []string{"9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42"}},
		{Name: "@operato/shell", Versions: []string{"9.0.22", "9.0.35", "9.0.36", "9.0.37", "9.0.38", "9.0.39"}},
		{Name: "@operato/styles", Versions: []string{"9.0.2", "9.0.35", "9.0.36", "9.0.37"}},
		{Name: "@operato/utils", Versions: []string{"9.0.22", "9.0.35", "9.0.36", "9.0.37", "9.0.38", "9.0.39", "9.0.40", "9.0.41", "9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46", "9.0.49"}},
		{Name: "@orbitgtbelgium/mapbox-gl-draw-cut-polygon-mode", Versions: []string{"2.0.5"}},
		{Name: "@orbitgtbelgium/mapbox-gl-draw-scale-rotate-mode", Versions: []string{"1.1.1"}},
		{Name: "@orbitgtbelgium/orbit-components", Versions: []string{"1.2.9"}},
		{Name: "@orbitgtbelgium/time-slider", Versions: []string{"1.0.187"}},
		{Name: "@osmanekrem/bmad", Versions: []string{"1.0.6"}},
		{Name: "@osmanekrem/error-handler", Versions: []string{"1.2.2"}},
		{Name: "@pergel/cli", Versions: []string{"0.11.1"}},
		{Name: "@pergel/module-box", Versions: []string{"0.6.1"}},
		{Name: "@pergel/module-graphql", Versions: []string{"0.6.1"}},
		{Name: "@pergel/module-ui", Versions: []string{"0.0.9"}},
		{Name: "@pergel/nuxt", Versions: []string{"0.25.5"}},
		{Name: "@posthog/agent", Versions: []string{"1.24.1"}},
		{Name: "@posthog/ai", Versions: []string{"7.1.2"}},
		{Name: "@posthog/automatic-cohorts-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/bitbucket-release-tracker", Versions: []string{"0.0.8"}},
		{Name: "@posthog/cli", Versions: []string{"0.5.15"}},
		{Name: "@posthog/clickhouse", Versions: []string{"1.7.1"}},
		{Name: "@posthog/core", Versions: []string{"1.5.6"}},
		{Name: "@posthog/currency-normalization-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/customerio-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/databricks-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/drop-events-on-property-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/event-sequence-timer-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/filter-out-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/first-time-event-tracker", Versions: []string{"0.0.8"}},
		{Name: "@posthog/geoip-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/github-release-tracking-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/gitub-star-sync-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/heartbeat-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/hedgehog-mode", Versions: []string{"0.0.42"}},
		{Name: "@posthog/icons", Versions: []string{"0.36.1"}},
		{Name: "@posthog/ingestion-alert-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/intercom-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/kinesis-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/laudspeaker-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/lemon-ui", Versions: []string{"0.0.1"}},
		{Name: "@posthog/maxmind-plugin", Versions: []string{"0.1.6"}},
		{Name: "@posthog/migrator3000-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/netdata-event-processing", Versions: []string{"0.0.8"}},
		{Name: "@posthog/nextjs", Versions: []string{"0.0.3"}},
		{Name: "@posthog/nextjs-config", Versions: []string{"1.5.1"}},
		{Name: "@posthog/nuxt", Versions: []string{"1.2.9"}},
		{Name: "@posthog/pagerduty-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/piscina", Versions: []string{"3.2.1"}},
		{Name: "@posthog/plugin-contrib", Versions: []string{"0.0.6"}},
		{Name: "@posthog/plugin-server", Versions: []string{"1.10.8"}},
		{Name: "@posthog/plugin-unduplicates", Versions: []string{"0.0.8"}},
		{Name: "@posthog/postgres-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/react-rrweb-player", Versions: []string{"1.1.4"}},
		{Name: "@posthog/rrdom", Versions: []string{"0.0.31"}},
		{Name: "@posthog/rrweb", Versions: []string{"0.0.31"}},
		{Name: "@posthog/rrweb-player", Versions: []string{"0.0.31"}},
		{Name: "@posthog/rrweb-record", Versions: []string{"0.0.31"}},
		{Name: "@posthog/rrweb-replay", Versions: []string{"0.0.19"}},
		{Name: "@posthog/rrweb-snapshot", Versions: []string{"0.0.31"}},
		{Name: "@posthog/rrweb-utils", Versions: []string{"0.0.31"}},
		{Name: "@posthog/sendgrid-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/siphash", Versions: []string{"1.1.2"}},
		{Name: "@posthog/snowflake-export-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/taxonomy-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/twilio-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/twitter-followers-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/url-normalizer-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/variance-plugin", Versions: []string{"0.0.8"}},
		{Name: "@posthog/web-dev-server", Versions: []string{"1.0.5"}},
		{Name: "@posthog/wizard", Versions: []string{"1.18.1"}},
		{Name: "@posthog/zendesk-plugin", Versions: []string{"0.0.8"}},
		{Name: "@postman/aether-icons", Versions: []string{"2.23.2", "2.23.3", "2.23.4"}},
		{Name: "@postman/csv-parse", Versions: []string{"4.0.3", "4.0.4", "4.0.5"}},
		{Name: "@postman/final-node-keytar", Versions: []string{"7.9.1", "7.9.2", "7.9.3"}},
		{Name: "@postman/mcp-ui-client", Versions: []string{"5.5.1", "5.5.2", "5.5.3"}},
		{Name: "@postman/node-keytar", Versions: []string{"7.9.4", "7.9.5", "7.9.6"}},
		{Name: "@postman/pm-bin-linux-x64", Versions: []string{"1.24.3", "1.24.4", "1.24.5"}},
		{Name: "@postman/pm-bin-macos-arm64", Versions: []string{"1.24.3", "1.24.4", "1.24.5"}},
		{Name: "@postman/pm-bin-macos-x64", Versions: []string{"1.24.3", "1.24.4", "1.24.5"}},
		{Name: "@postman/pm-bin-windows-x64", Versions: []string{"1.24.3", "1.24.4", "1.24.5"}},
		{Name: "@postman/postman-collection-fork", Versions: []string{"4.3.3", "4.3.4", "4.3.5"}},
		{Name: "@postman/postman-mcp-cli", Versions: []string{"1.0.3", "1.0.4", "1.0.5"}},
		{Name: "@postman/postman-mcp-server", Versions: []string{"2.4.10", "2.4.11", "2.4.12"}},
		{Name: "@postman/pretty-ms", Versions: []string{"6.1.1", "6.1.2", "6.1.3"}},
		{Name: "@postman/secret-scanner-wasm", Versions: []string{"2.1.2", "2.1.3", "2.1.4"}},
		{Name: "@postman/tunnel-agent", Versions: []string{"0.6.5", "0.6.6", "0.6.7"}},
		{Name: "@postman/wdio-allure-reporter", Versions: []string{"0.0.7", "0.0.8", "0.0.9"}},
		{Name: "@postman/wdio-junit-reporter", Versions: []string{"0.0.4", "0.0.5", "0.0.6"}},
		{Name: "@pradhumngautam/common-app", Versions: []string{"1.0.2"}},
		{Name: "@productdevbook/animejs-vue", Versions: []string{"0.2.1"}},
		{Name: "@productdevbook/auth", Versions: []string{"0.2.2"}},
		{Name: "@productdevbook/chatwoot", Versions: []string{"2.0.1"}},
		{Name: "@productdevbook/motion", Versions: []string{"1.0.4"}},
		{Name: "@productdevbook/ts-i18n", Versions: []string{"1.4.2"}},
		{Name: "@pruthvi21/use-debounce", Versions: []string{"1.0.3"}},
		{Name: "@quick-start-soft/quick-document-translator", Versions: []string{"1.4.2511142126"}},
		{Name: "@quick-start-soft/quick-git-clean-markdown", Versions: []string{"1.4.2511142126"}},
		{Name: "@quick-start-soft/quick-markdown", Versions: []string{"1.4.2511142126"}},
		{Name: "@quick-start-soft/quick-markdown-compose", Versions: []string{"1.4.2506300029"}},
		{Name: "@quick-start-soft/quick-markdown-image", Versions: []string{"1.4.2511142126"}},
		{Name: "@quick-start-soft/quick-markdown-print", Versions: []string{"1.4.2511142126"}},
		{Name: "@quick-start-soft/quick-markdown-translator", Versions: []string{"1.4.2509202331"}},
		{Name: "@quick-start-soft/quick-remove-image-background", Versions: []string{"1.4.2511142126"}},
		{Name: "@quick-start-soft/quick-task-refine", Versions: []string{"1.4.2511142126"}},
		{Name: "@relyt/claude-context-core", Versions: []string{"0.1.1"}},
		{Name: "@relyt/claude-context-mcp", Versions: []string{"0.1.1"}},
		{Name: "@relyt/mcp-server-relytone", Versions: []string{"0.0.3"}},
		{Name: "@sameepsi/sor", Versions: []string{"1.0.3"}},
		{Name: "@sameepsi/sor2", Versions: []string{"2.0.2"}},
		{Name: "@seezo/sdr-mcp-server", Versions: []string{"0.0.5"}},
		{Name: "@seung-ju/next", Versions: []string{"0.0.2"}},
		{Name: "@seung-ju/openapi-generator", Versions: []string{"0.0.4"}},
		{Name: "@seung-ju/react-hooks", Versions: []string{"0.0.2"}},
		{Name: "@seung-ju/react-native-action-sheet", Versions: []string{"0.2.1"}},
		{Name: "@silgi/better-auth", Versions: []string{"0.8.1"}},
		{Name: "@silgi/drizzle", Versions: []string{"0.8.4"}},
		{Name: "@silgi/ecosystem", Versions: []string{"0.7.6"}},
		{Name: "@silgi/graphql", Versions: []string{"0.7.15"}},
		{Name: "@silgi/module-builder", Versions: []string{"0.8.8"}},
		{Name: "@silgi/openapi", Versions: []string{"0.7.4"}},
		{Name: "@silgi/permission", Versions: []string{"0.6.8"}},
		{Name: "@silgi/ratelimit", Versions: []string{"0.2.1"}},
		{Name: "@silgi/scalar", Versions: []string{"0.6.2"}},
		{Name: "@silgi/yoga", Versions: []string{"0.7.1"}},
		{Name: "@sme-ui/aoma-vevasound-metadata-lib", Versions: []string{"0.1.3"}},
		{Name: "@strapbuild/react-native-date-time-picker", Versions: []string{"2.0.4"}},
		{Name: "@strapbuild/react-native-perspective-image-cropper", Versions: []string{"0.4.15"}},
		{Name: "@strapbuild/react-native-perspective-image-cropper-2", Versions: []string{"0.4.7"}},
		{Name: "@strapbuild/react-native-perspective-image-cropper-poojan31", Versions: []string{"0.4.6"}},
		{Name: "@suraj_h/medium-common", Versions: []string{"1.0.5"}},
		{Name: "@teselagen/bio-parsers", Versions: []string{"0.4.30"}},
		{Name: "@teselagen/bounce-loader", Versions: []string{"0.3.16", "0.3.17"}},
		{Name: "@teselagen/file-utils", Versions: []string{"0.3.22"}},
		{Name: "@teselagen/liquibase-tools", Versions: []string{"0.4.1"}},
		{Name: "@teselagen/ove", Versions: []string{"0.7.40"}},
		{Name: "@teselagen/range-utils", Versions: []string{"0.3.14", "0.3.15"}},
		{Name: "@teselagen/react-list", Versions: []string{"0.8.19", "0.8.20"}},
		{Name: "@teselagen/react-table", Versions: []string{"6.10.19", "6.10.20", "6.10.22"}},
		{Name: "@teselagen/sequence-utils", Versions: []string{"0.3.34"}},
		{Name: "@teselagen/ui", Versions: []string{"0.9.10"}},
		{Name: "@thangved/callback-window", Versions: []string{"1.1.4"}},
		{Name: "@thedelta/eslint-config", Versions: []string{"1.0.2"}},
		{Name: "@things-factory/attachment-base", Versions: []string{"9.0.43", "9.0.44", "9.0.45", "9.0.46", "9.0.47", "9.0.48", "9.0.49", "9.0.50"}},
		{Name: "@things-factory/auth-base", Versions: []string{"9.0.43", "9.0.44", "9.0.45"}},
		{Name: "@things-factory/email-base", Versions: []string{"9.0.42", "9.0.43", "9.0.44", "9.0.45", "9.0.46", "9.0.47", "9.0.48", "9.0.49", "9.0.50", "9.0.51", "9.0.52", "9.0.53", "9.0.54"}},
		{Name: "@things-factory/env", Versions: []string{"9.0.42", "9.0.43", "9.0.44", "9.0.45"}},
		{Name: "@things-factory/integration-base", Versions: []string{"9.0.43", "9.0.44", "9.0.45"}},
		{Name: "@things-factory/integration-marketplace", Versions: []string{"9.0.43", "9.0.44", "9.0.45"}},
		{Name: "@things-factory/shell", Versions: []string{"9.0.43", "9.0.44", "9.0.45"}},
		{Name: "@tiaanduplessis/json", Versions: []string{"2.0.2", "2.0.3"}},
		{Name: "@tiaanduplessis/react-progressbar", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "@tnf-dev/api", Versions: []string{"1.0.8"}},
		{Name: "@tnf-dev/core", Versions: []string{"1.0.8"}},
		{Name: "@tnf-dev/js", Versions: []string{"1.0.8"}},
		{Name: "@tnf-dev/mui", Versions: []string{"1.0.8"}},
		{Name: "@tnf-dev/react", Versions: []string{"1.0.8"}},
		{Name: "@trackstar/angular-trackstar-link", Versions: []string{"1.0.2"}},
		{Name: "@trackstar/react-trackstar-link", Versions: []string{"2.0.21"}},
		{Name: "@trackstar/react-trackstar-link-upgrade", Versions: []string{"1.1.10"}},
		{Name: "@trackstar/test-angular-package", Versions: []string{"0.0.9"}},
		{Name: "@trackstar/test-package", Versions: []string{"1.1.5"}},
		{Name: "@trefox/sleekshop-js", Versions: []string{"0.1.6"}},
		{Name: "@trigo/atrix", Versions: []string{"7.0.1"}},
		{Name: "@trigo/atrix-acl", Versions: []string{"4.0.2"}},
		{Name: "@trigo/atrix-elasticsearch", Versions: []string{"2.0.1"}},
		{Name: "@trigo/atrix-mongoose", Versions: []string{"1.0.2"}},
		{Name: "@trigo/atrix-orientdb", Versions: []string{"1.0.2"}},
		{Name: "@trigo/atrix-postgres", Versions: []string{"1.0.3"}},
		{Name: "@trigo/atrix-pubsub", Versions: []string{"4.0.3"}},
		{Name: "@trigo/atrix-redis", Versions: []string{"1.0.2"}},
		{Name: "@trigo/atrix-soap", Versions: []string{"1.0.2"}},
		{Name: "@trigo/atrix-swagger", Versions: []string{"3.0.1"}},
		{Name: "@trigo/bool-expressions", Versions: []string{"4.1.3"}},
		{Name: "@trigo/eslint-config-trigo", Versions: []string{"3.3.1"}},
		{Name: "@trigo/fsm", Versions: []string{"3.4.2"}},
		{Name: "@trigo/hapi-auth-signedlink", Versions: []string{"1.3.1"}},
		{Name: "@trigo/jsdt", Versions: []string{"0.2.1"}},
		{Name: "@trigo/keycloak-api", Versions: []string{"1.3.1"}},
		{Name: "@trigo/node-soap", Versions: []string{"0.5.4"}},
		{Name: "@trigo/pathfinder-ui-css", Versions: []string{"0.1.1"}},
		{Name: "@trigo/trigo-hapijs", Versions: []string{"5.0.1"}},
		{Name: "@trpc-rate-limiter/cloudflare", Versions: []string{"0.1.4"}},
		{Name: "@trpc-rate-limiter/hono", Versions: []string{"0.1.4"}},
		{Name: "@ui-ux-gang/devextreme-angular-rpk", Versions: []string{"24.1.7"}},
		{Name: "@varsityvibe/api-client", Versions: []string{"1.3.36", "1.3.37"}},
		{Name: "@varsityvibe/utils", Versions: []string{"5.0.6"}},
		{Name: "@varsityvibe/validation-schemas", Versions: []string{"0.6.7", "0.6.8"}},
		{Name: "@viapip/eslint-config", Versions: []string{"0.2.4"}},
		{Name: "@vishadtyagi/full-year-calendar", Versions: []string{"0.1.11"}},
		{Name: "@voiceflow/alexa-types", Versions: []string{"2.15.60", "2.15.61"}},
		{Name: "@voiceflow/anthropic", Versions: []string{"0.4.4", "0.4.5"}},
		{Name: "@voiceflow/api-sdk", Versions: []string{"3.28.58", "3.28.59"}},
		{Name: "@voiceflow/backend-utils", Versions: []string{"5.0.1", "5.0.2"}},
		{Name: "@voiceflow/base-types", Versions: []string{"2.136.2", "2.136.3"}},
		{Name: "@voiceflow/body-parser", Versions: []string{"1.21.2", "1.21.3"}},
		{Name: "@voiceflow/chat-types", Versions: []string{"2.14.58", "2.14.59"}},
		{Name: "@voiceflow/circleci-config-sdk-orb-import", Versions: []string{"0.2.1", "0.2.2"}},
		{Name: "@voiceflow/commitlint-config", Versions: []string{"2.6.1", "2.6.2"}},
		{Name: "@voiceflow/common", Versions: []string{"8.9.1", "8.9.2"}},
		{Name: "@voiceflow/default-prompt-wrappers", Versions: []string{"1.7.3", "1.7.4"}},
		{Name: "@voiceflow/dependency-cruiser-config", Versions: []string{"1.8.11", "1.8.12"}},
		{Name: "@voiceflow/dtos-interact", Versions: []string{"1.40.1", "1.40.2"}},
		{Name: "@voiceflow/encryption", Versions: []string{"0.3.2", "0.3.3"}},
		{Name: "@voiceflow/eslint-config", Versions: []string{"7.16.4", "7.16.5"}},
		{Name: "@voiceflow/eslint-plugin", Versions: []string{"1.6.1", "1.6.2"}},
		{Name: "@voiceflow/exception", Versions: []string{"1.10.1", "1.10.2"}},
		{Name: "@voiceflow/fetch", Versions: []string{"1.11.1", "1.11.2"}},
		{Name: "@voiceflow/general-types", Versions: []string{"3.2.22", "3.2.23"}},
		{Name: "@voiceflow/git-branch-check", Versions: []string{"1.4.3", "1.4.4"}},
		{Name: "@voiceflow/google-dfes-types", Versions: []string{"2.17.12", "2.17.13"}},
		{Name: "@voiceflow/google-types", Versions: []string{"2.21.12", "2.21.13"}},
		{Name: "@voiceflow/husky-config", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "@voiceflow/logger", Versions: []string{"2.4.2", "2.4.3"}},
		{Name: "@voiceflow/metrics", Versions: []string{"1.5.1", "1.5.2"}},
		{Name: "@voiceflow/natural-language-commander", Versions: []string{"0.5.2", "0.5.3"}},
		{Name: "@voiceflow/nestjs-common", Versions: []string{"2.75.2", "2.75.3"}},
		{Name: "@voiceflow/nestjs-mongodb", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "@voiceflow/nestjs-rate-limit", Versions: []string{"1.3.2", "1.3.3"}},
		{Name: "@voiceflow/nestjs-redis", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "@voiceflow/nestjs-timeout", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "@voiceflow/npm-package-json-lint-config", Versions: []string{"1.1.1", "1.1.2"}},
		{Name: "@voiceflow/openai", Versions: []string{"3.2.2", "3.2.3"}},
		{Name: "@voiceflow/pino", Versions: []string{"6.11.3", "6.11.4"}},
		{Name: "@voiceflow/pino-pretty", Versions: []string{"4.4.1", "4.4.2"}},
		{Name: "@voiceflow/prettier-config", Versions: []string{"1.10.1", "1.10.2"}},
		{Name: "@voiceflow/react-chat", Versions: []string{"1.65.3", "1.65.4"}},
		{Name: "@voiceflow/runtime", Versions: []string{"1.29.1", "1.29.2"}},
		{Name: "@voiceflow/runtime-client-js", Versions: []string{"1.17.2", "1.17.3"}},
		{Name: "@voiceflow/sdk-runtime", Versions: []string{"1.43.1", "1.43.2"}},
		{Name: "@voiceflow/secrets-provider", Versions: []string{"1.9.2", "1.9.3"}},
		{Name: "@voiceflow/semantic-release-config", Versions: []string{"1.4.1", "1.4.2"}},
		{Name: "@voiceflow/serverless-plugin-typescript", Versions: []string{"2.1.7", "2.1.8"}},
		{Name: "@voiceflow/slate-serializer", Versions: []string{"1.7.3", "1.7.4"}},
		{Name: "@voiceflow/stitches-react", Versions: []string{"2.3.2", "2.3.3"}},
		{Name: "@voiceflow/storybook-config", Versions: []string{"1.2.2", "1.2.3"}},
		{Name: "@voiceflow/stylelint-config", Versions: []string{"1.1.1", "1.1.2"}},
		{Name: "@voiceflow/test-common", Versions: []string{"2.1.1", "2.1.2"}},
		{Name: "@voiceflow/tsconfig", Versions: []string{"1.12.1", "1.12.2"}},
		{Name: "@voiceflow/tsconfig-paths", Versions: []string{"1.1.4", "1.1.5"}},
		{Name: "@voiceflow/utils-designer", Versions: []string{"1.74.19", "1.74.20"}},
		{Name: "@voiceflow/verror", Versions: []string{"1.1.4", "1.1.5"}},
		{Name: "@voiceflow/vite-config", Versions: []string{"2.6.2", "2.6.3"}},
		{Name: "@voiceflow/vitest-config", Versions: []string{"1.10.2", "1.10.3"}},
		{Name: "@voiceflow/voice-types", Versions: []string{"2.10.58", "2.10.59"}},
		{Name: "@voiceflow/voiceflow-types", Versions: []string{"3.32.45", "3.32.46"}},
		{Name: "@voiceflow/widget", Versions: []string{"1.7.18", "1.7.19"}},
		{Name: "@vucod/email", Versions: []string{"0.0.3"}},
		{Name: "@yoobic/design-system", Versions: []string{"6.5.17"}},
		{Name: "@yoobic/jpeg-camera-es6", Versions: []string{"1.0.13"}},
		{Name: "@yoobic/yobi", Versions: []string{"8.7.53"}},
		{Name: "@zapier/ai-actions", Versions: []string{"0.1.18", "0.1.19", "0.1.20"}},
		{Name: "@zapier/ai-actions-react", Versions: []string{"0.1.12", "0.1.13", "0.1.14"}},
		{Name: "@zapier/babel-preset-zapier", Versions: []string{"6.4.1", "6.4.2", "6.4.3"}},
		{Name: "@zapier/browserslist-config-zapier", Versions: []string{"1.0.3", "1.0.4", "1.0.5"}},
		{Name: "@zapier/eslint-plugin-zapier", Versions: []string{"11.0.3", "11.0.4", "11.0.5"}},
		{Name: "@zapier/mcp-integration", Versions: []string{"3.0.1", "3.0.2", "3.0.3"}},
		{Name: "@zapier/secret-scrubber", Versions: []string{"1.1.3", "1.1.4", "1.1.5"}},
		{Name: "@zapier/spectral-api-ruleset", Versions: []string{"1.9.1", "1.9.2", "1.9.3"}},
		{Name: "@zapier/stubtree", Versions: []string{"0.1.2", "0.1.3", "0.1.4"}},
		{Name: "@zapier/zapier-sdk", Versions: []string{"0.15.5", "0.15.6", "0.15.7"}},
		{Name: "ai-crowl-shield", Versions: []string{"1.0.7"}},
		{Name: "airchief", Versions: []string{"0.3.1"}},
		{Name: "airpilot", Versions: []string{"0.8.8"}},
		{Name: "angulartics2", Versions: []string{"14.1.1", "14.1.2"}},
		{Name: "arc-cli-fc", Versions: []string{"1.0.1"}},
		{Name: "asciitranslator", Versions: []string{"1.0.3"}},
		{Name: "asyncapi-preview", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "atrix", Versions: []string{"1.0.1"}},
		{Name: "atrix-mongoose", Versions: []string{"1.0.1"}},
		{Name: "automation_model", Versions: []string{"1.0.491"}},
		{Name: "avvvatars-vue", Versions: []string{"1.1.2"}},
		{Name: "axios-builder", Versions: []string{"1.2.1"}},
		{Name: "axios-cancelable", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "axios-timed", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "babel-preset-kinvey-flex-service", Versions: []string{"0.10.1"}},
		{Name: "barebones-css", Versions: []string{"1.1.3", "1.1.4"}},
		{Name: "benmostyn-frame-print", Versions: []string{"1.0.1"}},
		{Name: "best_gpio_controller", Versions: []string{"1.0.10"}},
		{Name: "better-auth-nuxt", Versions: []string{"0.0.10"}},
		{Name: "better-queue-nedb", Versions: []string{"0.10.5"}},
		{Name: "bidirectional-adapter", Versions: []string{"1.2.2", "1.2.3", "1.2.4", "1.2.5"}},
		{Name: "blinqio-executions-cli", Versions: []string{"1.0.41"}},
		{Name: "blob-to-base64", Versions: []string{"1.0.3"}},
		{Name: "bool-expressions", Versions: []string{"0.1.2"}},
		{Name: "browser-webdriver-downloader", Versions: []string{"3.0.8"}},
		{Name: "buffered-interpolation-babylon6", Versions: []string{"0.2.8"}},
		{Name: "bun-plugin-httpfile", Versions: []string{"0.1.1"}},
		{Name: "bytecode-checker-cli", Versions: []string{"1.0.10", "1.0.11", "1.0.8", "1.0.9"}},
		{Name: "bytes-to-x", Versions: []string{"1.0.1"}},
		{Name: "calc-loan-interest", Versions: []string{"1.0.4"}},
		{Name: "capacitor-notificationhandler", Versions: []string{"0.0.2", "0.0.3"}},
		{Name: "capacitor-plugin-apptrackingios", Versions: []string{"0.0.21"}},
		{Name: "capacitor-plugin-healthapp", Versions: []string{"0.0.2", "0.0.3"}},
		{Name: "capacitor-plugin-ihealth", Versions: []string{"1.1.8", "1.1.9"}},
		{Name: "capacitor-plugin-purchase", Versions: []string{"0.1.1"}},
		{Name: "capacitor-plugin-scgssigninwithgoogle", Versions: []string{"0.0.5"}},
		{Name: "capacitor-plugin-vonage", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "capacitor-purchase-history", Versions: []string{"0.0.10"}},
		{Name: "capacitor-voice-recorder-wav", Versions: []string{"6.0.3"}},
		{Name: "capacitorandroidpermissions", Versions: []string{"0.0.4", "0.0.5"}},
		{Name: "ceviz", Versions: []string{"0.0.5"}},
		{Name: "chrome-extension-downloads", Versions: []string{"0.0.3", "0.0.4"}},
		{Name: "claude-token-updater", Versions: []string{"1.0.3"}},
		{Name: "coinmarketcap-api", Versions: []string{"3.1.2", "3.1.3"}},
		{Name: "colors-regex", Versions: []string{"2.0.1"}},
		{Name: "command-irail", Versions: []string{"0.5.4"}},
		{Name: "compare-obj", Versions: []string{"1.1.1", "1.1.2"}},
		{Name: "composite-reducer", Versions: []string{"1.0.2", "1.0.3", "1.0.4", "1.0.5"}},
		{Name: "config-cordova", Versions: []string{"0.8.5"}},
		{Name: "cordova-plugin-voxeet2", Versions: []string{"1.0.24"}},
		{Name: "cordova-voxeet", Versions: []string{"1.0.32"}},
		{Name: "count-it-down", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "cpu-instructions", Versions: []string{"0.0.14"}},
		{Name: "create-director-app", Versions: []string{"0.1.1"}},
		{Name: "create-glee-app", Versions: []string{"0.2.2", "0.2.3"}},
		{Name: "create-hardhat3-app", Versions: []string{"1.1.1", "1.1.2", "1.1.3", "1.1.4"}},
		{Name: "create-hest-app", Versions: []string{"0.1.9"}},
		{Name: "create-kinvey-flex-service", Versions: []string{"0.20.1"}},
		{Name: "create-mcp-use-app", Versions: []string{"0.5.3", "0.5.4"}},
		{Name: "create-silgi", Versions: []string{"0.3.1"}},
		{Name: "crypto-addr-codec", Versions: []string{"0.1.9"}},
		{Name: "css-dedoupe", Versions: []string{"0.1.2"}},
		{Name: "csv-tool-cli", Versions: []string{"1.2.1"}},
		{Name: "dashboard-empty-state", Versions: []string{"1.0.3"}},
		{Name: "db-evo", Versions: []string{"1.1.4", "1.1.5"}},
		{Name: "designstudiouiux", Versions: []string{"1.0.1"}},
		{Name: "devextreme-angular-rpk", Versions: []string{"21.2.8"}},
		{Name: "devstart-cli", Versions: []string{"1.0.6"}},
		{Name: "dialogflow-es", Versions: []string{"1.1.1", "1.1.2", "1.1.3", "1.1.4"}},
		{Name: "discord-bot-server", Versions: []string{"0.1.2"}},
		{Name: "docusaurus-plugin-vanilla-extract", Versions: []string{"1.0.3"}},
		{Name: "dont-go", Versions: []string{"1.1.2"}},
		{Name: "dotnet-template", Versions: []string{"0.0.3", "0.0.4"}},
		{Name: "drop-events-on-property-plugin", Versions: []string{"0.0.2"}},
		{Name: "easypanel-sdk", Versions: []string{"0.3.2"}},
		{Name: "electron-volt", Versions: []string{"0.0.2"}},
		{Name: "email-deliverability-tester", Versions: []string{"1.1.1"}},
		{Name: "ember-browser-services", Versions: []string{"5.0.2", "5.0.3"}},
		{Name: "ember-headless-form", Versions: []string{"1.1.2", "1.1.3"}},
		{Name: "ember-headless-form-yup", Versions: []string{"1.0.1"}},
		{Name: "ember-headless-table", Versions: []string{"2.1.5", "2.1.6"}},
		{Name: "ember-url-hash-polyfill", Versions: []string{"1.0.12", "1.0.13"}},
		{Name: "ember-velcro", Versions: []string{"2.2.1", "2.2.2"}},
		{Name: "encounter-playground", Versions: []string{"0.0.2", "0.0.3", "0.0.4", "0.0.5"}},
		{Name: "enforce-branch-name", Versions: []string{"1.1.3"}},
		{Name: "esbuild-plugin-brotli", Versions: []string{"0.2.1"}},
		{Name: "esbuild-plugin-eta", Versions: []string{"0.1.1"}},
		{Name: "esbuild-plugin-httpfile", Versions: []string{"0.4.1"}},
		{Name: "eslint-config-crowdstrike", Versions: []string{"11.0.2", "11.0.3"}},
		{Name: "eslint-config-crowdstrike-node", Versions: []string{"4.0.3", "4.0.4"}},
		{Name: "eslint-config-kinvey-flex-service", Versions: []string{"0.10.1"}},
		{Name: "eslint-config-nitpicky", Versions: []string{"4.0.1"}},
		{Name: "eslint-config-teselagen", Versions: []string{"6.1.7", "6.1.8"}},
		{Name: "eslint-config-trigo", Versions: []string{"22.0.2"}},
		{Name: "eslint-config-zeallat-base", Versions: []string{"1.0.4"}},
		{Name: "ethereum-ens", Versions: []string{"0.8.1"}},
		{Name: "evm-checkcode-cli", Versions: []string{"1.0.12", "1.0.13", "1.0.14", "1.0.15"}},
		{Name: "exact-ticker", Versions: []string{"0.3.5"}},
		{Name: "expo-audio-session", Versions: []string{"0.2.1"}},
		{Name: "expo-router-on-rails", Versions: []string{"0.0.4"}},
		{Name: "express-starter-template", Versions: []string{"1.0.10"}},
		{Name: "expressos", Versions: []string{"1.1.3"}},
		{Name: "fat-fingered", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "feature-flip", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "firestore-search-engine", Versions: []string{"1.2.3"}},
		{Name: "fittxt", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "flapstacks", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "flatten-unflatten", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "formik-error-focus", Versions: []string{"2.0.1"}},
		{Name: "formik-store", Versions: []string{"1.0.1"}},
		{Name: "frontity-starter-theme", Versions: []string{"1.0.1"}},
		{Name: "fuzzy-finder", Versions: []string{"1.0.5", "1.0.6"}},
		{Name: "gate-evm-check-code2", Versions: []string{"2.0.3", "2.0.4", "2.0.5", "2.0.6"}},
		{Name: "gate-evm-tools-test", Versions: []string{"1.0.5", "1.0.6", "1.0.7", "1.0.8"}},
		{Name: "gatsby-plugin-antd", Versions: []string{"2.2.1"}},
		{Name: "gatsby-plugin-cname", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "generator-meteor-stock", Versions: []string{"0.1.6"}},
		{Name: "generator-ng-itobuz", Versions: []string{"0.0.15"}},
		{Name: "get-them-args", Versions: []string{"1.3.3"}},
		{Name: "github-action-for-generator", Versions: []string{"2.1.27", "2.1.28"}},
		{Name: "gitsafe", Versions: []string{"1.0.5"}},
		{Name: "globalize-rpk", Versions: []string{"1.7.4"}},
		{Name: "go-template", Versions: []string{"0.1.8", "0.1.9"}},
		{Name: "graphql-sequelize-teselagen", Versions: []string{"5.3.8", "5.3.9"}},
		{Name: "gulp-inject-envs", Versions: []string{"1.2.1", "1.2.2"}},
		{Name: "haufe-axera-api-client", Versions: []string{"0.0.1", "0.0.2"}},
		{Name: "hope-mapboxdraw", Versions: []string{"0.1.1"}},
		{Name: "hopedraw", Versions: []string{"1.0.3"}},
		{Name: "hover-design-prototype", Versions: []string{"0.0.5"}},
		{Name: "html-to-base64-image", Versions: []string{"1.0.2"}},
		{Name: "httpness", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "hyper-fullfacing", Versions: []string{"1.0.3"}},
		{Name: "hyperterm-hipster", Versions: []string{"1.0.7"}},
		{Name: "ids-css", Versions: []string{"1.5.1"}},
		{Name: "ids-enterprise-mcp-server", Versions: []string{"0.0.2"}},
		{Name: "ids-enterprise-ng", Versions: []string{"20.1.6"}},
		{Name: "ids-enterprise-typings", Versions: []string{"20.1.6"}},
		{Name: "image-to-uri", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "insomnia-plugin-random-pick", Versions: []string{"1.0.4"}},
		{Name: "invo", Versions: []string{"0.2.2"}},
		{Name: "iron-shield-miniapp", Versions: []string{"0.0.2"}},
		{Name: "ito-button", Versions: []string{"8.0.3"}},
		{Name: "itobuz-angular", Versions: []string{"0.0.1"}},
		{Name: "itobuz-angular-auth", Versions: []string{"8.0.11"}},
		{Name: "itobuz-angular-button", Versions: []string{"8.0.11"}},
		{Name: "jacob-zuma", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "jaetut-varit-test", Versions: []string{"1.0.2"}},
		{Name: "jan-browser", Versions: []string{"0.13.1"}},
		{Name: "jquery-bindings", Versions: []string{"1.1.2", "1.1.3"}},
		{Name: "json-rules-engine-simplified", Versions: []string{"0.2.1", "0.2.4"}},
		{Name: "jsonsurge", Versions: []string{"1.0.7"}},
		{Name: "jumpgate", Versions: []string{"0.0.2"}},
		{Name: "just-toasty", Versions: []string{"1.7.1"}},
		{Name: "kill-port", Versions: []string{"2.0.2", "2.0.3"}},
		{Name: "kinetix-default-token-list", Versions: []string{"1.0.5"}},
		{Name: "kinvey-cli-wrapper", Versions: []string{"0.30.1"}},
		{Name: "kinvey-flex-scripts", Versions: []string{"0.50.1"}},
		{Name: "kns-error-code", Versions: []string{"1.0.8"}},
		{Name: "koa2-swagger-ui", Versions: []string{"5.11.1", "5.11.2"}},
		{Name: "korea-administrative-area-geo-json-util", Versions: []string{"1.0.7"}},
		{Name: "kwami", Versions: []string{"1.5.10", "1.5.9"}},
		{Name: "lang-codes", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "license-o-matic", Versions: []string{"1.2.1", "1.2.2"}},
		{Name: "lint-staged-imagemin", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "lite-serper-mcp-server", Versions: []string{"0.2.2"}},
		{Name: "lui-vue-test", Versions: []string{"0.70.9"}},
		{Name: "luno-api", Versions: []string{"1.2.3"}},
		{Name: "m25-transaction-utils", Versions: []string{"1.1.16"}},
		{Name: "manual-billing-system-miniapp-api", Versions: []string{"1.3.1"}},
		{Name: "mcfly-semantic-release", Versions: []string{"1.3.1"}},
		{Name: "mcp-knowledge-base", Versions: []string{"0.0.2"}},
		{Name: "mcp-knowledge-graph", Versions: []string{"1.2.1"}},
		{Name: "mcp-use", Versions: []string{"1.4.2", "1.4.3"}},
		{Name: "medusa-plugin-announcement", Versions: []string{"0.0.3"}},
		{Name: "medusa-plugin-logs", Versions: []string{"0.0.17"}},
		{Name: "medusa-plugin-momo", Versions: []string{"0.0.68"}},
		{Name: "medusa-plugin-product-reviews-kvy", Versions: []string{"0.0.4"}},
		{Name: "medusa-plugin-zalopay", Versions: []string{"0.0.40"}},
		{Name: "mobioffice-cli", Versions: []string{"1.0.3"}},
		{Name: "mod10-check-digit", Versions: []string{"1.0.1"}},
		{Name: "mon-package-react-typescript", Versions: []string{"1.0.1"}},
		{Name: "monorepo-next", Versions: []string{"13.0.1", "13.0.2"}},
		{Name: "mstate-angular", Versions: []string{"0.4.4"}},
		{Name: "mstate-cli", Versions: []string{"0.4.7"}},
		{Name: "mstate-dev-react", Versions: []string{"1.1.1"}},
		{Name: "mstate-react", Versions: []string{"1.6.5"}},
		{Name: "my-saeed-lib", Versions: []string{"0.1.1"}},
		{Name: "n8n-nodes-tmdb", Versions: []string{"0.5.1"}},
		{Name: "n8n-nodes-vercel-ai-sdk", Versions: []string{"0.1.7"}},
		{Name: "n8n-nodes-viral-app", Versions: []string{"0.2.5"}},
		{Name: "nanoreset", Versions: []string{"7.0.1", "7.0.2"}},
		{Name: "next-circular-dependency", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "next-simple-google-analytics", Versions: []string{"1.1.1", "1.1.2"}},
		{Name: "next-styled-nprogress", Versions: []string{"1.0.4", "1.0.5"}},
		{Name: "ng2-file-upload", Versions: []string{"7.0.2", "7.0.3", "8.0.1", "8.0.2", "8.0.3", "9.0.1"}},
		{Name: "ngx-bootstrap", Versions: []string{"18.1.4", "19.0.3", "19.0.4", "20.0.3", "20.0.4", "20.0.5"}},
		{Name: "ngx-color", Versions: []string{"10.0.1", "10.0.2"}},
		{Name: "ngx-toastr", Versions: []string{"19.0.1", "19.0.2"}},
		{Name: "ngx-trend", Versions: []string{"8.0.1"}},
		{Name: "ngx-useful-swiper-prosenjit", Versions: []string{"9.0.2"}},
		{Name: "ngx-wooapi", Versions: []string{"12.0.1"}},
		{Name: "ngx-ws", Versions: []string{"1.1.5", "1.1.6"}},
		{Name: "nitro-graphql", Versions: []string{"1.5.12"}},
		{Name: "nitro-kutu", Versions: []string{"0.1.1"}},
		{Name: "nitrodeploy", Versions: []string{"1.0.8"}},
		{Name: "nitroping", Versions: []string{"0.1.1"}},
		{Name: "normal-store", Versions: []string{"1.3.1", "1.3.2", "1.3.3", "1.3.4"}},
		{Name: "nuxt-keycloak", Versions: []string{"0.2.2"}},
		{Name: "obj-to-css", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "okta-react-router-6", Versions: []string{"5.0.1"}},
		{Name: "open2internet", Versions: []string{"0.1.1"}},
		{Name: "oradm-to-gql", Versions: []string{"35.0.14", "35.0.15"}},
		{Name: "oradm-to-sqlz", Versions: []string{"1.1.2", "1.1.5"}},
		{Name: "orbit-boxicons", Versions: []string{"2.1.3"}},
		{Name: "orbit-nebula-draw-tools", Versions: []string{"1.0.10"}},
		{Name: "orbit-nebula-editor", Versions: []string{"1.0.2"}},
		{Name: "orbit-soap", Versions: []string{"0.43.13"}},
		{Name: "orchestrix", Versions: []string{"12.1.2"}},
		{Name: "ove-auto-annotate", Versions: []string{"0.0.9", "0.0.10"}},
		{Name: "package-tester", Versions: []string{"1.0.1"}},
		{Name: "parcel-plugin-asset-copier", Versions: []string{"1.1.2", "1.1.3"}},
		{Name: "pdf-annotation", Versions: []string{"0.0.2"}},
		{Name: "pergel", Versions: []string{"0.13.2"}},
		{Name: "pergeltest", Versions: []string{"0.0.25"}},
		{Name: "piclite", Versions: []string{"1.0.1"}},
		{Name: "pico-uid", Versions: []string{"1.0.3", "1.0.4"}},
		{Name: "pkg-readme", Versions: []string{"1.1.1"}},
		{Name: "pm2-gelf-json", Versions: []string{"1.0.4", "1.0.5"}},
		{Name: "poper-react-sdk", Versions: []string{"0.1.2"}},
		{Name: "posthog-docusaurus", Versions: []string{"2.0.6"}},
		{Name: "posthog-js", Versions: []string{"1.297.3"}},
		{Name: "posthog-node", Versions: []string{"4.18.1", "5.11.3", "5.13.3"}},
		{Name: "posthog-plugin-hello-world", Versions: []string{"1.0.1"}},
		{Name: "posthog-react-native", Versions: []string{"4.11.1", "4.12.5"}},
		{Name: "posthog-react-native-session-replay", Versions: []string{"1.2.2"}},
		{Name: "prime-one-table", Versions: []string{"0.0.19"}},
		{Name: "printjs-rpk", Versions: []string{"1.6.1"}},
		{Name: "prompt-eng", Versions: []string{"1.0.50"}},
		{Name: "prompt-eng-server", Versions: []string{"1.0.18"}},
		{Name: "puny-req", Versions: []string{"1.0.3"}},
		{Name: "quickswap-ads-list", Versions: []string{"1.0.33"}},
		{Name: "quickswap-default-staking-list", Versions: []string{"1.0.11"}},
		{Name: "quickswap-default-staking-list-address", Versions: []string{"1.0.55"}},
		{Name: "quickswap-default-token-list", Versions: []string{"1.5.16"}},
		{Name: "quickswap-router-sdk", Versions: []string{"1.0.1"}},
		{Name: "quickswap-sdk", Versions: []string{"3.0.44"}},
		{Name: "quickswap-smart-order-router", Versions: []string{"1.0.1"}},
		{Name: "quickswap-token-lists", Versions: []string{"1.0.3"}},
		{Name: "quickswap-v2-sdk", Versions: []string{"2.0.1"}},
		{Name: "ra-auth-firebase", Versions: []string{"1.0.3"}},
		{Name: "ra-data-firebase", Versions: []string{"1.0.7", "1.0.8"}},
		{Name: "react-complaint-image", Versions: []string{"0.0.32", "0.0.35"}},
		{Name: "react-component-taggers", Versions: []string{"0.1.9"}},
		{Name: "react-data-to-export", Versions: []string{"1.0.1"}},
		{Name: "react-element-prompt-inspector", Versions: []string{"0.1.18"}},
		{Name: "react-favic", Versions: []string{"1.0.2"}},
		{Name: "react-hook-form-persist", Versions: []string{"3.0.1", "3.0.2"}},
		{Name: "react-jam-icons", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "react-jsonschema-form-conditionals", Versions: []string{"0.3.18", "0.3.21"}},
		{Name: "react-jsonschema-form-extras", Versions: []string{"1.0.4"}},
		{Name: "react-jsonschema-rxnt-extras", Versions: []string{"0.4.9"}},
		{Name: "react-keycloak-context", Versions: []string{"1.0.8", "1.0.9"}},
		{Name: "react-library-setup", Versions: []string{"0.0.6"}},
		{Name: "react-linear-loader", Versions: []string{"1.0.2"}},
		{Name: "react-micromodal.js", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "react-native-datepicker-modal", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "react-native-email", Versions: []string{"2.1.1", "2.1.2"}},
		{Name: "react-native-fetch", Versions: []string{"2.0.1", "2.0.2"}},
		{Name: "react-native-get-pixel-dimensions", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "react-native-google-maps-directions", Versions: []string{"2.1.2"}},
		{Name: "react-native-jam-icons", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "react-native-log-level", Versions: []string{"1.2.1", "1.2.2"}},
		{Name: "react-native-modest-checkbox", Versions: []string{"3.3.1"}},
		{Name: "react-native-modest-storage", Versions: []string{"2.1.1"}},
		{Name: "react-native-phone-call", Versions: []string{"1.2.1", "1.2.2"}},
		{Name: "react-native-retriable-fetch", Versions: []string{"2.0.1", "2.0.2"}},
		{Name: "react-native-use-modal", Versions: []string{"1.0.3"}},
		{Name: "react-native-view-finder", Versions: []string{"1.2.1", "1.2.2"}},
		{Name: "react-native-websocket", Versions: []string{"1.0.3", "1.0.4"}},
		{Name: "react-native-worklet-functions", Versions: []string{"3.3.3"}},
		{Name: "react-packery-component", Versions: []string{"1.0.3"}},
		{Name: "react-qr-image", Versions: []string{"1.1.1"}},
		{Name: "react-scrambled-text", Versions: []string{"1.0.4"}},
		{Name: "rediff", Versions: []string{"1.0.5"}},
		{Name: "rediff-viewer", Versions: []string{"0.0.7"}},
		{Name: "redux-forge", Versions: []string{"2.5.3"}},
		{Name: "redux-router-kit", Versions: []string{"1.2.2", "1.2.3", "1.2.4"}},
		{Name: "remark-preset-lint-crowdstrike", Versions: []string{"4.0.1", "4.0.2"}},
		{Name: "revenuecat", Versions: []string{"1.0.1"}},
		{Name: "rollup-plugin-httpfile", Versions: []string{"0.2.1"}},
		{Name: "rxnt-authentication", Versions: []string{"0.0.3", "0.0.4", "0.0.5", "0.0.6"}},
		{Name: "rxnt-healthchecks-nestjs", Versions: []string{"1.0.2", "1.0.3", "1.0.4", "1.0.5"}},
		{Name: "rxnt-kue", Versions: []string{"1.0.4", "1.0.5", "1.0.6", "1.0.7"}},
		{Name: "sa-company-registration-number-regex", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "sa-id-gen", Versions: []string{"1.0.4", "1.0.5"}},
		{Name: "samesame", Versions: []string{"1.0.3"}},
		{Name: "scgs-capacitor-subscribe", Versions: []string{"1.0.11"}},
		{Name: "scgsffcreator", Versions: []string{"1.0.5"}},
		{Name: "schob", Versions: []string{"1.0.3"}},
		{Name: "selenium-session", Versions: []string{"1.0.5"}},
		{Name: "selenium-session-client", Versions: []string{"1.0.4"}},
		{Name: "set-nested-prop", Versions: []string{"2.0.1", "2.0.2"}},
		{Name: "shelf-jwt-sessions", Versions: []string{"0.1.2"}},
		{Name: "shell-exec", Versions: []string{"1.1.3", "1.1.4"}},
		{Name: "shinhan-limit-scrap", Versions: []string{"1.0.3"}},
		{Name: "silgi", Versions: []string{"0.43.30"}},
		{Name: "simple-swizzle", Versions: []string{"0.2.3"}},
		{Name: "simplejsonform", Versions: []string{"1.0.1"}},
		{Name: "skills-use", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "slice-ansi", Versions: []string{"7.1.1"}},
		{Name: "solomon-api-stories", Versions: []string{"1.0.2"}},
		{Name: "solomon-v3-stories", Versions: []string{"1.15.6"}},
		{Name: "solomon-v3-ui-wrapper", Versions: []string{"1.6.1"}},
		{Name: "soneium-acs", Versions: []string{"1.0.1"}},
		{Name: "sort-by-distance", Versions: []string{"2.0.1"}},
		{Name: "south-african-id-info", Versions: []string{"1.0.2"}},
		{Name: "stat-fns", Versions: []string{"1.0.1"}},
		{Name: "stoor", Versions: []string{"2.3.2"}},
		{Name: "strip-ansi", Versions: []string{"7.1.1"}},
		{Name: "sufetch", Versions: []string{"0.4.1"}},
		{Name: "super-commit", Versions: []string{"1.0.1"}},
		{Name: "supports-color", Versions: []string{"10.2.1"}},
		{Name: "supports-hyperlinks", Versions: []string{"4.1.1"}},
		{Name: "svelte-autocomplete-select", Versions: []string{"1.1.1"}},
		{Name: "svelte-toasty", Versions: []string{"1.1.2", "1.1.3"}},
		{Name: "swc-plugin-component-annotate", Versions: []string{"1.9.1", "1.9.2"}},
		{Name: "tanstack-shadcn-table", Versions: []string{"1.1.5"}},
		{Name: "tavily-module", Versions: []string{"1.0.1"}},
		{Name: "tbssnch", Versions: []string{"1.0.2"}},
		{Name: "tcsp", Versions: []string{"2.0.2"}},
		{Name: "tcsp-draw-test", Versions: []string{"1.0.5"}},
		{Name: "tcsp-test-vd", Versions: []string{"2.4.4"}},
		{Name: "template-lib", Versions: []string{"1.1.3", "1.1.4"}},
		{Name: "template-micro-service", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "tenacious-fetch", Versions: []string{"2.3.2", "2.3.3"}},
		{Name: "teselagen-interval-tree", Versions: []string{"1.1.2"}},
		{Name: "test-foundry-app", Versions: []string{"1.0.1", "1.0.2", "1.0.3", "1.0.4"}},
		{Name: "test-hardhat-app", Versions: []string{"1.0.1", "1.0.2", "1.0.3", "1.0.4"}},
		{Name: "test23112222-api", Versions: []string{"1.0.1"}},
		{Name: "tg-client-query-builder", Versions: []string{"2.14.4", "2.14.5"}},
		{Name: "tg-redbird", Versions: []string{"1.3.1", "1.3.2"}},
		{Name: "tg-seq-gen", Versions: []string{"1.0.9", "1.0.10"}},
		{Name: "thangved-react-grid", Versions: []string{"1.0.3"}},
		{Name: "tiaan", Versions: []string{"1.0.2"}},
		{Name: "tiptap-shadcn-vue", Versions: []string{"0.2.1"}},
		{Name: "token.js-fork", Versions: []string{"0.7.32"}},
		{Name: "toonfetch", Versions: []string{"0.3.2"}},
		{Name: "trigo-react-app", Versions: []string{"4.1.2"}},
		{Name: "ts-gaussian", Versions: []string{"3.0.5", "3.0.6"}},
		{Name: "ts-imports", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "ts-relay-cursor-paging", Versions: []string{"2.1.1"}},
		{Name: "tvi-cli", Versions: []string{"0.1.5"}},
		{Name: "typeface-antonio-complete", Versions: []string{"1.0.5"}},
		{Name: "typefence", Versions: []string{"1.2.2", "1.2.3"}},
		{Name: "typeorm-orbit", Versions: []string{"0.2.27"}},
		{Name: "unadapter", Versions: []string{"0.1.3"}},
		{Name: "undefsafe-typed", Versions: []string{"1.0.3", "1.0.4"}},
		{Name: "unemail", Versions: []string{"0.3.1"}},
		{Name: "uniswap-router-sdk", Versions: []string{"1.6.2"}},
		{Name: "uniswap-smart-order-router", Versions: []string{"3.16.26"}},
		{Name: "uniswap-test-sdk-core", Versions: []string{"4.0.8"}},
		{Name: "unsearch", Versions: []string{"0.0.3"}},
		{Name: "uplandui", Versions: []string{"0.5.4"}},
		{Name: "upload-to-play-store", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "url-encode-decode", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "use-unsaved-changes", Versions: []string{"1.0.9"}},
		{Name: "v-plausible", Versions: []string{"1.2.1"}},
		{Name: "valid-south-african-id", Versions: []string{"1.0.3"}},
		{Name: "valuedex-sdk", Versions: []string{"3.0.5"}},
		{Name: "ve-bamreader", Versions: []string{"0.2.6", "0.2.7"}},
		{Name: "ve-editor", Versions: []string{"1.0.1", "1.0.2"}},
		{Name: "verror-extra", Versions: []string{"6.0.1"}},
		{Name: "vf-oss-template", Versions: []string{"1.0.1", "1.0.2", "1.0.3", "1.0.4"}},
		{Name: "victoria-wallet-constants", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "victoria-wallet-core", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "victoria-wallet-type", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "victoria-wallet-utils", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "victoria-wallet-validator", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "victoriaxoaquyet-wallet-core", Versions: []string{"0.2.1", "0.2.2"}},
		{Name: "vite-plugin-httpfile", Versions: []string{"0.2.1"}},
		{Name: "voip-callkit", Versions: []string{"1.0.2", "1.0.3"}},
		{Name: "vue-browserupdate-nuxt", Versions: []string{"1.0.5"}},
		{Name: "wallet-evm", Versions: []string{"0.3.1", "0.3.2"}},
		{Name: "wallet-type", Versions: []string{"0.1.1", "0.1.2"}},
		{Name: "wdio-web-reporter", Versions: []string{"0.1.3"}},
		{Name: "web-scraper-mcp", Versions: []string{"1.1.4"}},
		{Name: "web-types-htmx", Versions: []string{"0.1.1"}},
		{Name: "web-types-lit", Versions: []string{"0.1.1"}},
		{Name: "webpack-loader-httpfile", Versions: []string{"0.2.1"}},
		{Name: "wellness-expert-ng-gallery", Versions: []string{"5.1.1"}},
		{Name: "wenk", Versions: []string{"1.0.10", "1.0.9"}},
		{Name: "wrap-ansi", Versions: []string{"9.0.1"}},
		{Name: "yargs-help-output", Versions: []string{"5.0.3"}},
		{Name: "yoo-styles", Versions: []string{"6.0.326"}},
		{Name: "zapier-async-storage", Versions: []string{"1.0.1", "1.0.2", "1.0.3"}},
		{Name: "zapier-platform-cli", Versions: []string{"18.0.2", "18.0.3", "18.0.4"}},
		{Name: "zapier-platform-core", Versions: []string{"18.0.2", "18.0.3", "18.0.4"}},
		{Name: "zapier-platform-legacy-scripting-runner", Versions: []string{"4.0.2", "4.0.3", "4.0.4"}},
		{Name: "zapier-platform-schema", Versions: []string{"18.0.2", "18.0.3", "18.0.4"}},
		{Name: "zapier-scripts", Versions: []string{"7.8.3", "7.8.4"}},
		{Name: "zuper-cli", Versions: []string{"1.0.1"}},
		{Name: "zuper-sdk", Versions: []string{"1.0.57"}},
		{Name: "zuper-stream", Versions: []string{"2.0.9"}},
	}
}
